#!/bin/bash
# Railway Environment Variables Setup Script

echo "=== Railway Environment Variables Setup ==="
echo ""
echo "Copy these variables to Railway Dashboard -> Your Service -> Variables tab"
echo ""
echo "1. DATABASE_URL"
echo "   ACTION REQUIRED: Get this from Railway PostgreSQL -> Variables tab"
echo "   Format: postgresql://postgres:password@host:5432/railway"
echo ""
echo "2. NEXTAUTH_SECRET"
echo "   Value: F9kv4UQvY9QjkN+mp9RsDDYsfjFF/n6H582SHO671uY="
echo ""
echo "3. NEXTAUTH_URL"
echo "   ACTION REQUIRED: Update with your Railway app URL after deployment"
echo "   Format: https://your-app-name.railway.app"
echo ""
echo "4. WHISPER_SERVICE_URL"
echo "   Value: http://18.204.48.204:8000"
echo ""
echo "5. WHISPER_API_KEY"
echo "   Value: 16e90a8598c12bcf2606a34a4e04fda5b0c7c4f3b2cadcbc5d8ddb61ca9b5189"
echo ""
echo "For detailed instructions, see: RAILWAY_ENV_VARS.md"
